import uuid
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class AIAnalyticsContext(BaseModel):
    """Structured, sanitized context passed to the AI provider for insight generation."""
    profile: Dict[str, Any]
    growth: Dict[str, Any]
    engagement: Dict[str, Any]
    content: Dict[str, Any]
    frequency: Dict[str, Any]
    anomalies: List[Dict[str, Any]]
    days: Optional[int] = None


class AIObservation(BaseModel):
    """Single analytical observation categorized by metric domain."""
    category: str = Field(description="Category: growth, engagement, content, frequency, or anomaly")
    statement: str = Field(description="Factual, analytical statement explaining the metric observation")
    supporting_metrics: List[str] = Field(default_factory=list, description="List of specific numerical metrics supporting statement")


class AIInsight(BaseModel):
    """Structured output generated by the AI Insight layer."""
    title: str = Field(description="Headline summary title for the profile analytics")
    summary: str = Field(description="Concise paragraph explaining profile trends based on observations")
    observations: List[AIObservation] = Field(default_factory=list, description="Categorized analytical observations")
    data_points: List[str] = Field(default_factory=list, description="Key metrics observed in the data context")
    limitations: Optional[str] = Field(None, description="Note regarding missing data or observation bounds")
    provider: str = Field(default="mock", description="Identifier of the LLM provider used")
    generated_at: str = Field(description="ISO timestamp when insight was generated")
