"""create socialscope core models

Revision ID: f21d8f69f6d9
Revises: 
Create Date: 2026-09-27 13:54:44.749862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21d8f69f6d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'X', 'FACEBOOK', name='social_platform_enum', native_enum=False), nullable=False),
    sa.Column('platform_profile_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_url', sa.String(length=1024), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=1024), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'username', name='uq_profile_platform_username')
    )
    op.create_index(op.f('ix_profiles_platform'), 'profiles', ['platform'], unique=False)
    op.create_index(op.f('ix_profiles_platform_profile_id'), 'profiles', ['platform_profile_id'], unique=False)
    op.create_index(op.f('ix_profiles_username'), 'profiles', ['username'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('baseline', sa.JSON(), nullable=True),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_detected_at'), 'anomalies', ['detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_profile_id'), 'anomalies', ['profile_id'], unique=False)
    op.create_table('collection_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'X', 'FACEBOOK', name='social_platform_enum', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='job_status_enum', native_enum=False), nullable=False),
    sa.Column('records_collected', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('collector_version', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_jobs_profile_id'), 'collection_jobs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_collection_jobs_started_at'), 'collection_jobs', ['started_at'], unique=False)
    op.create_index(op.f('ix_collection_jobs_status'), 'collection_jobs', ['status'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('media_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'platform_post_id', name='uq_post_profile_platform_post_id')
    )
    op.create_index(op.f('ix_posts_platform_post_id'), 'posts', ['platform_post_id'], unique=False)
    op.create_index(op.f('ix_posts_profile_id'), 'posts', ['profile_id'], unique=False)
    op.create_table('profile_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('followers', sa.BigInteger(), nullable=True),
    sa.Column('following', sa.BigInteger(), nullable=True),
    sa.Column('post_count', sa.BigInteger(), nullable=True),
    sa.Column('other_platform_metrics', sa.JSON(), nullable=True),
    sa.Column('collector_version', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_snapshots_collected_at'), 'profile_snapshots', ['collected_at'], unique=False)
    op.create_index(op.f('ix_profile_snapshots_profile_id'), 'profile_snapshots', ['profile_id'], unique=False)
    op.create_table('collection_errors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_job_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['collection_job_id'], ['collection_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_errors_collection_job_id'), 'collection_errors', ['collection_job_id'], unique=False)
    op.create_table('post_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('engagement', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_snapshots_collected_at'), 'post_snapshots', ['collected_at'], unique=False)
    op.create_index(op.f('ix_post_snapshots_post_id'), 'post_snapshots', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_snapshots_post_id'), table_name='post_snapshots')
    op.drop_index(op.f('ix_post_snapshots_collected_at'), table_name='post_snapshots')
    op.drop_table('post_snapshots')
    op.drop_index(op.f('ix_collection_errors_collection_job_id'), table_name='collection_errors')
    op.drop_table('collection_errors')
    op.drop_index(op.f('ix_profile_snapshots_profile_id'), table_name='profile_snapshots')
    op.drop_index(op.f('ix_profile_snapshots_collected_at'), table_name='profile_snapshots')
    op.drop_table('profile_snapshots')
    op.drop_index(op.f('ix_posts_profile_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_platform_post_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_collection_jobs_status'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_started_at'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_profile_id'), table_name='collection_jobs')
    op.drop_table('collection_jobs')
    op.drop_index(op.f('ix_anomalies_profile_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_detected_at'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_profiles_username'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_platform_profile_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_platform'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
