"""add_collection_schedule_to_profiles

Revision ID: fb3c16bb8f66
Revises: f21d8f69f6d9
Create Date: 2026-09-27 15:22:56.459550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3c16bb8f66'
down_revision: Union[str, Sequence[str], None] = 'f21d8f69f6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('collection_schedule', sa.Enum('manual', 'every_6_hours', 'every_12_hours', 'daily', name='collection_schedule_enum', native_enum=False), server_default='manual', nullable=False))
    op.add_column('profiles', sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_profiles_collection_schedule'), 'profiles', ['collection_schedule'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_collection_schedule'), table_name='profiles')
    op.drop_column('profiles', 'last_collected_at')
    op.drop_column('profiles', 'collection_schedule')
    # ### end Alembic commands ###
